# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_authority_response_is_the_response_type_for_query_authority import QueryAuthorityResponseIsTheResponseTypeForQueryAuthority  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryAuthorityResponseIsTheResponseTypeForQueryAuthority(unittest.TestCase):
    """QueryAuthorityResponseIsTheResponseTypeForQueryAuthority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryAuthorityResponseIsTheResponseTypeForQueryAuthority(self):
        """Test QueryAuthorityResponseIsTheResponseTypeForQueryAuthority"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_authority_response_is_the_response_type_for_query_authority.QueryAuthorityResponseIsTheResponseTypeForQueryAuthority()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
