# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_distribution_v1beta1_query_delegation_rewards_response_rewards import CosmosDistributionV1beta1QueryDelegationRewardsResponseRewards  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosDistributionV1beta1QueryDelegationRewardsResponseRewards(unittest.TestCase):
    """CosmosDistributionV1beta1QueryDelegationRewardsResponseRewards unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosDistributionV1beta1QueryDelegationRewardsResponseRewards(self):
        """Test CosmosDistributionV1beta1QueryDelegationRewardsResponseRewards"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_distribution_v1beta1_query_delegation_rewards_response_rewards.CosmosDistributionV1beta1QueryDelegationRewardsResponseRewards()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
