# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_nft_v1beta1_query_balance_response import CosmosNftV1beta1QueryBalanceResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosNftV1beta1QueryBalanceResponse(unittest.TestCase):
    """CosmosNftV1beta1QueryBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosNftV1beta1QueryBalanceResponse(self):
        """Test CosmosNftV1beta1QueryBalanceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_nft_v1beta1_query_balance_response.CosmosNftV1beta1QueryBalanceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
