# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmwasm_wasm_v1_query_contract_history_response_entries import CosmwasmWasmV1QueryContractHistoryResponseEntries  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmwasmWasmV1QueryContractHistoryResponseEntries(unittest.TestCase):
    """CosmwasmWasmV1QueryContractHistoryResponseEntries unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmwasmWasmV1QueryContractHistoryResponseEntries(self):
        """Test CosmwasmWasmV1QueryContractHistoryResponseEntries"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmwasm_wasm_v1_query_contract_history_response_entries.CosmwasmWasmV1QueryContractHistoryResponseEntries()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
