# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.contract_info_stores_awasm_contract_instance import ContractInfoStoresAWASMContractInstance  # noqa: E501
from swagger_client.rest import ApiException


class TestContractInfoStoresAWASMContractInstance(unittest.TestCase):
    """ContractInfoStoresAWASMContractInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContractInfoStoresAWASMContractInstance(self):
        """Test ContractInfoStoresAWASMContractInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.contract_info_stores_awasm_contract_instance.ContractInfoStoresAWASMContractInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
