# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_base_tendermint_v1beta1_block_evidence_light_client_attack_evidence_conflicting_block_signed_header_header import CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader(unittest.TestCase):
    """CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader(self):
        """Test CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_base_tendermint_v1beta1_block_evidence_light_client_attack_evidence_conflicting_block_signed_header_header.CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderHeader()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
