# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_gov_v1beta1_tally_params import CosmosGovV1beta1TallyParams  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGovV1beta1TallyParams(unittest.TestCase):
    """CosmosGovV1beta1TallyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGovV1beta1TallyParams(self):
        """Test CosmosGovV1beta1TallyParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_gov_v1beta1_tally_params.CosmosGovV1beta1TallyParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
