# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_consensus_v1_query_params_response_params_evidence import CosmosConsensusV1QueryParamsResponseParamsEvidence  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosConsensusV1QueryParamsResponseParamsEvidence(unittest.TestCase):
    """CosmosConsensusV1QueryParamsResponseParamsEvidence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosConsensusV1QueryParamsResponseParamsEvidence(self):
        """Test CosmosConsensusV1QueryParamsResponseParamsEvidence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_consensus_v1_query_params_response_params_evidence.CosmosConsensusV1QueryParamsResponseParamsEvidence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
