# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_base_tendermint_v1beta1_get_node_info_response_application_version import CosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion(unittest.TestCase):
    """CosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion(self):
        """Test CosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_base_tendermint_v1beta1_get_node_info_response_application_version.CosmosBaseTendermintV1beta1GetNodeInfoResponseApplicationVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
