# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_core_connection_v1_connection_end_counterparty import IbcCoreConnectionV1ConnectionEndCounterparty  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcCoreConnectionV1ConnectionEndCounterparty(unittest.TestCase):
    """IbcCoreConnectionV1ConnectionEndCounterparty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcCoreConnectionV1ConnectionEndCounterparty(self):
        """Test IbcCoreConnectionV1ConnectionEndCounterparty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_core_connection_v1_connection_end_counterparty.IbcCoreConnectionV1ConnectionEndCounterparty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
