# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.identified_packet_fees_contains_a_list_of_type_packet_fee_and_associated_packet_id import IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId  # noqa: E501
from swagger_client.rest import ApiException


class TestIdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId(unittest.TestCase):
    """IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId(self):
        """Test IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.identified_packet_fees_contains_a_list_of_type_packet_fee_and_associated_packet_id.IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
