# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_auth_v1beta1_params import CosmosAuthV1beta1Params  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosAuthV1beta1Params(unittest.TestCase):
    """CosmosAuthV1beta1Params unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosAuthV1beta1Params(self):
        """Test CosmosAuthV1beta1Params"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_auth_v1beta1_params.CosmosAuthV1beta1Params()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
