# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tendermint_p2p_default_node_info_other import TendermintP2pDefaultNodeInfoOther  # noqa: E501
from swagger_client.rest import ApiException


class TestTendermintP2pDefaultNodeInfoOther(unittest.TestCase):
    """TendermintP2pDefaultNodeInfoOther unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTendermintP2pDefaultNodeInfoOther(self):
        """Test TendermintP2pDefaultNodeInfoOther"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tendermint_p2p_default_node_info_other.TendermintP2pDefaultNodeInfoOther()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
