# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_group_v1_query_group_members_response import CosmosGroupV1QueryGroupMembersResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGroupV1QueryGroupMembersResponse(unittest.TestCase):
    """CosmosGroupV1QueryGroupMembersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGroupV1QueryGroupMembersResponse(self):
        """Test CosmosGroupV1QueryGroupMembersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_group_v1_query_group_members_response.CosmosGroupV1QueryGroupMembersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
