# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_base_abci_v1beta1_tx_response_logs import CosmosBaseAbciV1beta1TxResponseLogs  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosBaseAbciV1beta1TxResponseLogs(unittest.TestCase):
    """CosmosBaseAbciV1beta1TxResponseLogs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosBaseAbciV1beta1TxResponseLogs(self):
        """Test CosmosBaseAbciV1beta1TxResponseLogs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_base_abci_v1beta1_tx_response_logs.CosmosBaseAbciV1beta1TxResponseLogs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
