# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_evidence_v1beta1_query_evidence_response import CosmosEvidenceV1beta1QueryEvidenceResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosEvidenceV1beta1QueryEvidenceResponse(unittest.TestCase):
    """CosmosEvidenceV1beta1QueryEvidenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosEvidenceV1beta1QueryEvidenceResponse(self):
        """Test CosmosEvidenceV1beta1QueryEvidenceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_evidence_v1beta1_query_evidence_response.CosmosEvidenceV1beta1QueryEvidenceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
