# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmwasm_wasm_v1_params import CosmwasmWasmV1Params  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmwasmWasmV1Params(unittest.TestCase):
    """CosmwasmWasmV1Params unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmwasmWasmV1Params(self):
        """Test CosmwasmWasmV1Params"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmwasm_wasm_v1_params.CosmwasmWasmV1Params()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
