# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_staking_v1beta1_historical_info_commission import CosmosStakingV1beta1HistoricalInfoCommission  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosStakingV1beta1HistoricalInfoCommission(unittest.TestCase):
    """CosmosStakingV1beta1HistoricalInfoCommission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosStakingV1beta1HistoricalInfoCommission(self):
        """Test CosmosStakingV1beta1HistoricalInfoCommission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_staking_v1beta1_historical_info_commission.CosmosStakingV1beta1HistoricalInfoCommission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
