# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_core_client_v1_query_upgraded_client_state_response import IbcCoreClientV1QueryUpgradedClientStateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcCoreClientV1QueryUpgradedClientStateResponse(unittest.TestCase):
    """IbcCoreClientV1QueryUpgradedClientStateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcCoreClientV1QueryUpgradedClientStateResponse(self):
        """Test IbcCoreClientV1QueryUpgradedClientStateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_core_client_v1_query_upgraded_client_state_response.IbcCoreClientV1QueryUpgradedClientStateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
