# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmwasm_wasm_v1_query_raw_contract_state_response import CosmwasmWasmV1QueryRawContractStateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmwasmWasmV1QueryRawContractStateResponse(unittest.TestCase):
    """CosmwasmWasmV1QueryRawContractStateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmwasmWasmV1QueryRawContractStateResponse(self):
        """Test CosmwasmWasmV1QueryRawContractStateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmwasm_wasm_v1_query_raw_contract_state_response.CosmwasmWasmV1QueryRawContractStateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
