# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.deprecated_please_use_sdk_block_instead_evidence_light_client_attack_evidence_conflicting_block_signed_header import DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader  # noqa: E501
from swagger_client.rest import ApiException


class TestDeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader(unittest.TestCase):
    """DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader(self):
        """Test DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.deprecated_please_use_sdk_block_instead_evidence_light_client_attack_evidence_conflicting_block_signed_header.DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidenceConflictingBlockSignedHeader()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
