# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.msg_api import MsgApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMsgApi(unittest.TestCase):
    """MsgApi unit test stubs"""

    def setUp(self):
        self.api = MsgApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cosmos_group_v1_create_group(self):
        """Test case for cosmos_group_v1_create_group

        CreateGroup creates a new group with an admin account address, a list of members and some optional metadata.  # noqa: E501
        """
        pass

    def test_cosmos_group_v1_delete_group(self):
        """Test case for cosmos_group_v1_delete_group

        Delete the group and members with given group id and admin address.  # noqa: E501
        """
        pass

    def test_cosmos_group_v1_leave_group(self):
        """Test case for cosmos_group_v1_leave_group

        LeaveGroup allows a group member to leave the group.  # noqa: E501
        """
        pass

    def test_cosmos_group_v1_update_group_members(self):
        """Test case for cosmos_group_v1_update_group_members

        UpdateGroupMembers updates the group members with given group id and admin address.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
