# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_packet_commitment_response_defines_the_client_query_response_for_a_packetwhich_also_includes_a_proof_and_the_height_from_which_the_proof_wasretrieved import QueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved(unittest.TestCase):
    """QueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved(self):
        """Test QueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_packet_commitment_response_defines_the_client_query_response_for_a_packetwhich_also_includes_a_proof_and_the_height_from_which_the_proof_wasretrieved.QueryPacketCommitmentResponseDefinesTheClientQueryResponseForAPacketwhichAlsoIncludesAProofAndTheHeightFromWhichTheProofWasretrieved()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
