# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_gov_v1_query_deposits_response_deposits import CosmosGovV1QueryDepositsResponseDeposits  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGovV1QueryDepositsResponseDeposits(unittest.TestCase):
    """CosmosGovV1QueryDepositsResponseDeposits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGovV1QueryDepositsResponseDeposits(self):
        """Test CosmosGovV1QueryDepositsResponseDeposits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_gov_v1_query_deposits_response_deposits.CosmosGovV1QueryDepositsResponseDeposits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
