# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_fee_enabled_channels_response_defines_the_response_type_for_the_fee_enabled_channels_rpc import QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc(unittest.TestCase):
    """QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc(self):
        """Test QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_fee_enabled_channels_response_defines_the_response_type_for_the_fee_enabled_channels_rpc.QueryFeeEnabledChannelsResponseDefinesTheResponseTypeForTheFeeEnabledChannelsRpc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
