# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_gov_v1_query_deposits_response import CosmosGovV1QueryDepositsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGovV1QueryDepositsResponse(unittest.TestCase):
    """CosmosGovV1QueryDepositsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGovV1QueryDepositsResponse(self):
        """Test CosmosGovV1QueryDepositsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_gov_v1_query_deposits_response.CosmosGovV1QueryDepositsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
