# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmwasm_wasm_v1_query_params_response_params import CosmwasmWasmV1QueryParamsResponseParams  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmwasmWasmV1QueryParamsResponseParams(unittest.TestCase):
    """CosmwasmWasmV1QueryParamsResponseParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmwasmWasmV1QueryParamsResponseParams(self):
        """Test CosmwasmWasmV1QueryParamsResponseParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmwasm_wasm_v1_query_params_response_params.CosmwasmWasmV1QueryParamsResponseParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
