# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.grant_authorization_extends_a_grant_with_both_the_addresses_of_the_grantee_and_granter_it_is_used_in_genesis_proto_and_query_proto import GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto  # noqa: E501
from swagger_client.rest import ApiException


class TestGrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto(unittest.TestCase):
    """GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto(self):
        """Test GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.grant_authorization_extends_a_grant_with_both_the_addresses_of_the_grantee_and_granter_it_is_used_in_genesis_proto_and_query_proto.GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
