# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_tx_v1beta1_get_block_with_txs_response_pagination import CosmosTxV1beta1GetBlockWithTxsResponsePagination  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosTxV1beta1GetBlockWithTxsResponsePagination(unittest.TestCase):
    """CosmosTxV1beta1GetBlockWithTxsResponsePagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosTxV1beta1GetBlockWithTxsResponsePagination(self):
        """Test CosmosTxV1beta1GetBlockWithTxsResponsePagination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_tx_v1beta1_get_block_with_txs_response_pagination.CosmosTxV1beta1GetBlockWithTxsResponsePagination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
