# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_staking_v1beta1_fixed_deposit import CosmosStakingV1beta1FixedDeposit  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosStakingV1beta1FixedDeposit(unittest.TestCase):
    """CosmosStakingV1beta1FixedDeposit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosStakingV1beta1FixedDeposit(self):
        """Test CosmosStakingV1beta1FixedDeposit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_staking_v1beta1_fixed_deposit.CosmosStakingV1beta1FixedDeposit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
