# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_applications_transfer_v1_query_denom_traces_response import IbcApplicationsTransferV1QueryDenomTracesResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcApplicationsTransferV1QueryDenomTracesResponse(unittest.TestCase):
    """IbcApplicationsTransferV1QueryDenomTracesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcApplicationsTransferV1QueryDenomTracesResponse(self):
        """Test IbcApplicationsTransferV1QueryDenomTracesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_applications_transfer_v1_query_denom_traces_response.IbcApplicationsTransferV1QueryDenomTracesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
