# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_core_connection_v1_msg_connection_open_try_response import IbcCoreConnectionV1MsgConnectionOpenTryResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcCoreConnectionV1MsgConnectionOpenTryResponse(unittest.TestCase):
    """IbcCoreConnectionV1MsgConnectionOpenTryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcCoreConnectionV1MsgConnectionOpenTryResponse(self):
        """Test IbcCoreConnectionV1MsgConnectionOpenTryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_core_connection_v1_msg_connection_open_try_response.IbcCoreConnectionV1MsgConnectionOpenTryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
