# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_group_v1_group_member import CosmosGroupV1GroupMember  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosGroupV1GroupMember(unittest.TestCase):
    """CosmosGroupV1GroupMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosGroupV1GroupMember(self):
        """Test CosmosGroupV1GroupMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_group_v1_group_member.CosmosGroupV1GroupMember()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
