# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_feegrant_v1beta1_msg_revoke_allowance_response import CosmosFeegrantV1beta1MsgRevokeAllowanceResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosFeegrantV1beta1MsgRevokeAllowanceResponse(unittest.TestCase):
    """CosmosFeegrantV1beta1MsgRevokeAllowanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosFeegrantV1beta1MsgRevokeAllowanceResponse(self):
        """Test CosmosFeegrantV1beta1MsgRevokeAllowanceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_feegrant_v1beta1_msg_revoke_allowance_response.CosmosFeegrantV1beta1MsgRevokeAllowanceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
