# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_consensus_v1_query_params_response_params_block import CosmosConsensusV1QueryParamsResponseParamsBlock  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosConsensusV1QueryParamsResponseParamsBlock(unittest.TestCase):
    """CosmosConsensusV1QueryParamsResponseParamsBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosConsensusV1QueryParamsResponseParamsBlock(self):
        """Test CosmosConsensusV1QueryParamsResponseParamsBlock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_consensus_v1_query_params_response_params_block.CosmosConsensusV1QueryParamsResponseParamsBlock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
