# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_base_v1beta1_dec_coin import CosmosBaseV1beta1DecCoin  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosBaseV1beta1DecCoin(unittest.TestCase):
    """CosmosBaseV1beta1DecCoin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosBaseV1beta1DecCoin(self):
        """Test CosmosBaseV1beta1DecCoin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_base_v1beta1_dec_coin.CosmosBaseV1beta1DecCoin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
