# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_upgrade_v1beta1_query_module_versions_response_module_versions import CosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions(unittest.TestCase):
    """CosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions(self):
        """Test CosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_upgrade_v1beta1_query_module_versions_response_module_versions.CosmosUpgradeV1beta1QueryModuleVersionsResponseModuleVersions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
