# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_applications_fee_v1_query_incentivized_packets_response import IbcApplicationsFeeV1QueryIncentivizedPacketsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcApplicationsFeeV1QueryIncentivizedPacketsResponse(unittest.TestCase):
    """IbcApplicationsFeeV1QueryIncentivizedPacketsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcApplicationsFeeV1QueryIncentivizedPacketsResponse(self):
        """Test IbcApplicationsFeeV1QueryIncentivizedPacketsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_applications_fee_v1_query_incentivized_packets_response.IbcApplicationsFeeV1QueryIncentivizedPacketsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
