# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20091 import InlineResponse20091  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20091(unittest.TestCase):
    """InlineResponse20091 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20091(self):
        """Test InlineResponse20091"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20091.InlineResponse20091()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
