# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_params_v1beta1_query_params_response import CosmosParamsV1beta1QueryParamsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosParamsV1beta1QueryParamsResponse(unittest.TestCase):
    """CosmosParamsV1beta1QueryParamsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosParamsV1beta1QueryParamsResponse(self):
        """Test CosmosParamsV1beta1QueryParamsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_params_v1beta1_query_params_response.CosmosParamsV1beta1QueryParamsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
