# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ibc_applications_interchain_accounts_controller_v1_query_interchain_account_response import IbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestIbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse(unittest.TestCase):
    """IbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse(self):
        """Test IbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ibc_applications_interchain_accounts_controller_v1_query_interchain_account_response.IbcApplicationsInterchainAccountsControllerV1QueryInterchainAccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
