# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_tx_v1beta1_mode_info_single import CosmosTxV1beta1ModeInfoSingle  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosTxV1beta1ModeInfoSingle(unittest.TestCase):
    """CosmosTxV1beta1ModeInfoSingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosTxV1beta1ModeInfoSingle(self):
        """Test CosmosTxV1beta1ModeInfoSingle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_tx_v1beta1_mode_info_single.CosmosTxV1beta1ModeInfoSingle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
