# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.merkle_prefix_is_merkle_path_prefixed_to_the_key_the_constructed_key_from_the_path_and_the_key_will_be_append_path_key_pathappend_path_key_prefix_key_ import MerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_  # noqa: E501
from swagger_client.rest import ApiException


class TestMerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_(unittest.TestCase):
    """MerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_ unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_(self):
        """Test MerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.merkle_prefix_is_merkle_path_prefixed_to_the_key_the_constructed_key_from_the_path_and_the_key_will_be_append_path_key_pathappend_path_key_prefix_key_.MerklePrefixIsMerklePathPrefixedToTheKeyTheConstructedKeyFromThePathAndTheKeyWillBeAppendPathKeyPathappendPathKeyPrefixKey_()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
