# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_slashing_v1beta1_query_params_response_params import CosmosSlashingV1beta1QueryParamsResponseParams  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosSlashingV1beta1QueryParamsResponseParams(unittest.TestCase):
    """CosmosSlashingV1beta1QueryParamsResponseParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosSlashingV1beta1QueryParamsResponseParams(self):
        """Test CosmosSlashingV1beta1QueryParamsResponseParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_slashing_v1beta1_query_params_response_params.CosmosSlashingV1beta1QueryParamsResponseParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
