# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.code_info_response_contains_code_meta_data_from_code_info import CodeInfoResponseContainsCodeMetaDataFromCodeInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestCodeInfoResponseContainsCodeMetaDataFromCodeInfo(unittest.TestCase):
    """CodeInfoResponseContainsCodeMetaDataFromCodeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodeInfoResponseContainsCodeMetaDataFromCodeInfo(self):
        """Test CodeInfoResponseContainsCodeMetaDataFromCodeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.code_info_response_contains_code_meta_data_from_code_info.CodeInfoResponseContainsCodeMetaDataFromCodeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
