# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_staking_v1beta1_msg_create_validator_response import CosmosStakingV1beta1MsgCreateValidatorResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosStakingV1beta1MsgCreateValidatorResponse(unittest.TestCase):
    """CosmosStakingV1beta1MsgCreateValidatorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosStakingV1beta1MsgCreateValidatorResponse(self):
        """Test CosmosStakingV1beta1MsgCreateValidatorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_staking_v1beta1_msg_create_validator_response.CosmosStakingV1beta1MsgCreateValidatorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
