# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.query_payee_response_defines_the_response_type_for_the_payee_rpc import QueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc  # noqa: E501
from swagger_client.rest import ApiException


class TestQueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc(unittest.TestCase):
    """QueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc(self):
        """Test QueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.query_payee_response_defines_the_response_type_for_the_payee_rpc.QueryPayeeResponseDefinesTheResponseTypeForThePayeeRpc()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
