# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.height_is_a_monotonically_increasing_data_typethat_can_be_compared_against_another_height_for_the_purposes_of_updating_andfreezing_clients import HeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients  # noqa: E501
from swagger_client.rest import ApiException


class TestHeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients(unittest.TestCase):
    """HeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients(self):
        """Test HeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.height_is_a_monotonically_increasing_data_typethat_can_be_compared_against_another_height_for_the_purposes_of_updating_andfreezing_clients.HeightIsAMonotonicallyIncreasingDataTypethatCanBeComparedAgainstAnotherHeightForThePurposesOfUpdatingAndfreezingClients()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
