# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cosmos_bank_v1beta1_query_denoms_metadata_response_metadatas import CosmosBankV1beta1QueryDenomsMetadataResponseMetadatas  # noqa: E501
from swagger_client.rest import ApiException


class TestCosmosBankV1beta1QueryDenomsMetadataResponseMetadatas(unittest.TestCase):
    """CosmosBankV1beta1QueryDenomsMetadataResponseMetadatas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCosmosBankV1beta1QueryDenomsMetadataResponseMetadatas(self):
        """Test CosmosBankV1beta1QueryDenomsMetadataResponseMetadatas"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cosmos_bank_v1beta1_query_denoms_metadata_response_metadatas.CosmosBankV1beta1QueryDenomsMetadataResponseMetadatas()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
