# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosSlashingV1beta1Params(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'signed_blocks_window': 'str',
        'min_signed_per_window': 'str',
        'downtime_jail_duration': 'str',
        'slash_fraction_double_sign': 'str',
        'slash_fraction_downtime': 'str'
    }

    attribute_map = {
        'signed_blocks_window': 'signed_blocks_window',
        'min_signed_per_window': 'min_signed_per_window',
        'downtime_jail_duration': 'downtime_jail_duration',
        'slash_fraction_double_sign': 'slash_fraction_double_sign',
        'slash_fraction_downtime': 'slash_fraction_downtime'
    }

    def __init__(self, signed_blocks_window=None, min_signed_per_window=None, downtime_jail_duration=None, slash_fraction_double_sign=None, slash_fraction_downtime=None):  # noqa: E501
        """CosmosSlashingV1beta1Params - a model defined in Swagger"""  # noqa: E501
        self._signed_blocks_window = None
        self._min_signed_per_window = None
        self._downtime_jail_duration = None
        self._slash_fraction_double_sign = None
        self._slash_fraction_downtime = None
        self.discriminator = None
        if signed_blocks_window is not None:
            self.signed_blocks_window = signed_blocks_window
        if min_signed_per_window is not None:
            self.min_signed_per_window = min_signed_per_window
        if downtime_jail_duration is not None:
            self.downtime_jail_duration = downtime_jail_duration
        if slash_fraction_double_sign is not None:
            self.slash_fraction_double_sign = slash_fraction_double_sign
        if slash_fraction_downtime is not None:
            self.slash_fraction_downtime = slash_fraction_downtime

    @property
    def signed_blocks_window(self):
        """Gets the signed_blocks_window of this CosmosSlashingV1beta1Params.  # noqa: E501


        :return: The signed_blocks_window of this CosmosSlashingV1beta1Params.  # noqa: E501
        :rtype: str
        """
        return self._signed_blocks_window

    @signed_blocks_window.setter
    def signed_blocks_window(self, signed_blocks_window):
        """Sets the signed_blocks_window of this CosmosSlashingV1beta1Params.


        :param signed_blocks_window: The signed_blocks_window of this CosmosSlashingV1beta1Params.  # noqa: E501
        :type: str
        """

        self._signed_blocks_window = signed_blocks_window

    @property
    def min_signed_per_window(self):
        """Gets the min_signed_per_window of this CosmosSlashingV1beta1Params.  # noqa: E501


        :return: The min_signed_per_window of this CosmosSlashingV1beta1Params.  # noqa: E501
        :rtype: str
        """
        return self._min_signed_per_window

    @min_signed_per_window.setter
    def min_signed_per_window(self, min_signed_per_window):
        """Sets the min_signed_per_window of this CosmosSlashingV1beta1Params.


        :param min_signed_per_window: The min_signed_per_window of this CosmosSlashingV1beta1Params.  # noqa: E501
        :type: str
        """

        self._min_signed_per_window = min_signed_per_window

    @property
    def downtime_jail_duration(self):
        """Gets the downtime_jail_duration of this CosmosSlashingV1beta1Params.  # noqa: E501


        :return: The downtime_jail_duration of this CosmosSlashingV1beta1Params.  # noqa: E501
        :rtype: str
        """
        return self._downtime_jail_duration

    @downtime_jail_duration.setter
    def downtime_jail_duration(self, downtime_jail_duration):
        """Sets the downtime_jail_duration of this CosmosSlashingV1beta1Params.


        :param downtime_jail_duration: The downtime_jail_duration of this CosmosSlashingV1beta1Params.  # noqa: E501
        :type: str
        """

        self._downtime_jail_duration = downtime_jail_duration

    @property
    def slash_fraction_double_sign(self):
        """Gets the slash_fraction_double_sign of this CosmosSlashingV1beta1Params.  # noqa: E501


        :return: The slash_fraction_double_sign of this CosmosSlashingV1beta1Params.  # noqa: E501
        :rtype: str
        """
        return self._slash_fraction_double_sign

    @slash_fraction_double_sign.setter
    def slash_fraction_double_sign(self, slash_fraction_double_sign):
        """Sets the slash_fraction_double_sign of this CosmosSlashingV1beta1Params.


        :param slash_fraction_double_sign: The slash_fraction_double_sign of this CosmosSlashingV1beta1Params.  # noqa: E501
        :type: str
        """

        self._slash_fraction_double_sign = slash_fraction_double_sign

    @property
    def slash_fraction_downtime(self):
        """Gets the slash_fraction_downtime of this CosmosSlashingV1beta1Params.  # noqa: E501


        :return: The slash_fraction_downtime of this CosmosSlashingV1beta1Params.  # noqa: E501
        :rtype: str
        """
        return self._slash_fraction_downtime

    @slash_fraction_downtime.setter
    def slash_fraction_downtime(self, slash_fraction_downtime):
        """Sets the slash_fraction_downtime of this CosmosSlashingV1beta1Params.


        :param slash_fraction_downtime: The slash_fraction_downtime of this CosmosSlashingV1beta1Params.  # noqa: E501
        :type: str
        """

        self._slash_fraction_downtime = slash_fraction_downtime

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosSlashingV1beta1Params, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosSlashingV1beta1Params):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
