# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosNftV1beta1QueryClassesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'classes': 'list[CosmosNftV1beta1QueryClassesResponseClasses]',
        'pagination': 'CosmosAuthV1beta1QueryAccountsResponsePagination'
    }

    attribute_map = {
        'classes': 'classes',
        'pagination': 'pagination'
    }

    def __init__(self, classes=None, pagination=None):  # noqa: E501
        """CosmosNftV1beta1QueryClassesResponse - a model defined in Swagger"""  # noqa: E501
        self._classes = None
        self._pagination = None
        self.discriminator = None
        if classes is not None:
            self.classes = classes
        if pagination is not None:
            self.pagination = pagination

    @property
    def classes(self):
        """Gets the classes of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501

        class defines the class of the nft type.  # noqa: E501

        :return: The classes of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501
        :rtype: list[CosmosNftV1beta1QueryClassesResponseClasses]
        """
        return self._classes

    @classes.setter
    def classes(self, classes):
        """Sets the classes of this CosmosNftV1beta1QueryClassesResponse.

        class defines the class of the nft type.  # noqa: E501

        :param classes: The classes of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501
        :type: list[CosmosNftV1beta1QueryClassesResponseClasses]
        """

        self._classes = classes

    @property
    def pagination(self):
        """Gets the pagination of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501


        :return: The pagination of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501
        :rtype: CosmosAuthV1beta1QueryAccountsResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this CosmosNftV1beta1QueryClassesResponse.


        :param pagination: The pagination of this CosmosNftV1beta1QueryClassesResponse.  # noqa: E501
        :type: CosmosAuthV1beta1QueryAccountsResponsePagination
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosNftV1beta1QueryClassesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosNftV1beta1QueryClassesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
