# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosStakingV1beta1QueryPoolResponsePool(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'not_bonded_tokens': 'str',
        'bonded_tokens': 'str',
        'not_bonded_stake_tokens': 'str',
        'bonded_stake_tokens': 'str',
        'stake_tokens': 'str'
    }

    attribute_map = {
        'not_bonded_tokens': 'not_bonded_tokens',
        'bonded_tokens': 'bonded_tokens',
        'not_bonded_stake_tokens': 'not_bonded_stake_tokens',
        'bonded_stake_tokens': 'bonded_stake_tokens',
        'stake_tokens': 'stake_tokens'
    }

    def __init__(self, not_bonded_tokens=None, bonded_tokens=None, not_bonded_stake_tokens=None, bonded_stake_tokens=None, stake_tokens=None):  # noqa: E501
        """CosmosStakingV1beta1QueryPoolResponsePool - a model defined in Swagger"""  # noqa: E501
        self._not_bonded_tokens = None
        self._bonded_tokens = None
        self._not_bonded_stake_tokens = None
        self._bonded_stake_tokens = None
        self._stake_tokens = None
        self.discriminator = None
        if not_bonded_tokens is not None:
            self.not_bonded_tokens = not_bonded_tokens
        if bonded_tokens is not None:
            self.bonded_tokens = bonded_tokens
        if not_bonded_stake_tokens is not None:
            self.not_bonded_stake_tokens = not_bonded_stake_tokens
        if bonded_stake_tokens is not None:
            self.bonded_stake_tokens = bonded_stake_tokens
        if stake_tokens is not None:
            self.stake_tokens = stake_tokens

    @property
    def not_bonded_tokens(self):
        """Gets the not_bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501


        :return: The not_bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :rtype: str
        """
        return self._not_bonded_tokens

    @not_bonded_tokens.setter
    def not_bonded_tokens(self, not_bonded_tokens):
        """Sets the not_bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.


        :param not_bonded_tokens: The not_bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :type: str
        """

        self._not_bonded_tokens = not_bonded_tokens

    @property
    def bonded_tokens(self):
        """Gets the bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501


        :return: The bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :rtype: str
        """
        return self._bonded_tokens

    @bonded_tokens.setter
    def bonded_tokens(self, bonded_tokens):
        """Sets the bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.


        :param bonded_tokens: The bonded_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :type: str
        """

        self._bonded_tokens = bonded_tokens

    @property
    def not_bonded_stake_tokens(self):
        """Gets the not_bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501


        :return: The not_bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :rtype: str
        """
        return self._not_bonded_stake_tokens

    @not_bonded_stake_tokens.setter
    def not_bonded_stake_tokens(self, not_bonded_stake_tokens):
        """Sets the not_bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.


        :param not_bonded_stake_tokens: The not_bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :type: str
        """

        self._not_bonded_stake_tokens = not_bonded_stake_tokens

    @property
    def bonded_stake_tokens(self):
        """Gets the bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501


        :return: The bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :rtype: str
        """
        return self._bonded_stake_tokens

    @bonded_stake_tokens.setter
    def bonded_stake_tokens(self, bonded_stake_tokens):
        """Sets the bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.


        :param bonded_stake_tokens: The bonded_stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :type: str
        """

        self._bonded_stake_tokens = bonded_stake_tokens

    @property
    def stake_tokens(self):
        """Gets the stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501


        :return: The stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :rtype: str
        """
        return self._stake_tokens

    @stake_tokens.setter
    def stake_tokens(self, stake_tokens):
        """Sets the stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.


        :param stake_tokens: The stake_tokens of this CosmosStakingV1beta1QueryPoolResponsePool.  # noqa: E501
        :type: str
        """

        self._stake_tokens = stake_tokens

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosStakingV1beta1QueryPoolResponsePool, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosStakingV1beta1QueryPoolResponsePool):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
