# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fixed_deposit_annual_rate': 'CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponseFixedDepositAnnualRate',
        'pagination': 'CosmosSlashingV1beta1QuerySigningInfosResponsePagination'
    }

    attribute_map = {
        'fixed_deposit_annual_rate': 'FixedDepositAnnualRate',
        'pagination': 'pagination'
    }

    def __init__(self, fixed_deposit_annual_rate=None, pagination=None):  # noqa: E501
        """CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse - a model defined in Swagger"""  # noqa: E501
        self._fixed_deposit_annual_rate = None
        self._pagination = None
        self.discriminator = None
        if fixed_deposit_annual_rate is not None:
            self.fixed_deposit_annual_rate = fixed_deposit_annual_rate
        if pagination is not None:
            self.pagination = pagination

    @property
    def fixed_deposit_annual_rate(self):
        """Gets the fixed_deposit_annual_rate of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501


        :return: The fixed_deposit_annual_rate of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501
        :rtype: CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponseFixedDepositAnnualRate
        """
        return self._fixed_deposit_annual_rate

    @fixed_deposit_annual_rate.setter
    def fixed_deposit_annual_rate(self, fixed_deposit_annual_rate):
        """Sets the fixed_deposit_annual_rate of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.


        :param fixed_deposit_annual_rate: The fixed_deposit_annual_rate of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501
        :type: CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponseFixedDepositAnnualRate
        """

        self._fixed_deposit_annual_rate = fixed_deposit_annual_rate

    @property
    def pagination(self):
        """Gets the pagination of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501


        :return: The pagination of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501
        :rtype: CosmosSlashingV1beta1QuerySigningInfosResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.


        :param pagination: The pagination of this CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse.  # noqa: E501
        :type: CosmosSlashingV1beta1QuerySigningInfosResponsePagination
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosStakingV1beta1QueryGetFixedDepositInterestRateResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
