# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosBankV1beta1Input(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'coins': 'list[CosmosBankV1beta1InputCoins]'
    }

    attribute_map = {
        'address': 'address',
        'coins': 'coins'
    }

    def __init__(self, address=None, coins=None):  # noqa: E501
        """CosmosBankV1beta1Input - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._coins = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if coins is not None:
            self.coins = coins

    @property
    def address(self):
        """Gets the address of this CosmosBankV1beta1Input.  # noqa: E501


        :return: The address of this CosmosBankV1beta1Input.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CosmosBankV1beta1Input.


        :param address: The address of this CosmosBankV1beta1Input.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def coins(self):
        """Gets the coins of this CosmosBankV1beta1Input.  # noqa: E501


        :return: The coins of this CosmosBankV1beta1Input.  # noqa: E501
        :rtype: list[CosmosBankV1beta1InputCoins]
        """
        return self._coins

    @coins.setter
    def coins(self, coins):
        """Sets the coins of this CosmosBankV1beta1Input.


        :param coins: The coins of this CosmosBankV1beta1Input.  # noqa: E501
        :type: list[CosmosBankV1beta1InputCoins]
        """

        self._coins = coins

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosBankV1beta1Input, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosBankV1beta1Input):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
