# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CosmosGroupV1MsgLeaveGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin': 'str',
        'group_id': 'str',
        'address': 'str'
    }

    attribute_map = {
        'admin': 'admin',
        'group_id': 'group_id',
        'address': 'address'
    }

    def __init__(self, admin=None, group_id=None, address=None):  # noqa: E501
        """CosmosGroupV1MsgLeaveGroup - a model defined in Swagger"""  # noqa: E501
        self._admin = None
        self._group_id = None
        self._address = None
        self.discriminator = None
        if admin is not None:
            self.admin = admin
        if group_id is not None:
            self.group_id = group_id
        if address is not None:
            self.address = address

    @property
    def admin(self):
        """Gets the admin of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501


        :return: The admin of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :rtype: str
        """
        return self._admin

    @admin.setter
    def admin(self, admin):
        """Sets the admin of this CosmosGroupV1MsgLeaveGroup.


        :param admin: The admin of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :type: str
        """

        self._admin = admin

    @property
    def group_id(self):
        """Gets the group_id of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501

        group_id is the unique ID of the group.  # noqa: E501

        :return: The group_id of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this CosmosGroupV1MsgLeaveGroup.

        group_id is the unique ID of the group.  # noqa: E501

        :param group_id: The group_id of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def address(self):
        """Gets the address of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501

        address is the account address of the group member.  # noqa: E501

        :return: The address of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this CosmosGroupV1MsgLeaveGroup.

        address is the account address of the group member.  # noqa: E501

        :param address: The address of this CosmosGroupV1MsgLeaveGroup.  # noqa: E501
        :type: str
        """

        self._address = address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CosmosGroupV1MsgLeaveGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CosmosGroupV1MsgLeaveGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
