# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IbcCoreChannelV1QueryPacketAcknowledgementsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acknowledgements': 'list[IbcCoreChannelV1QueryPacketAcknowledgementsResponseAcknowledgements]',
        'pagination': 'PaginationResponse',
        'height': 'QueryBlockHeight'
    }

    attribute_map = {
        'acknowledgements': 'acknowledgements',
        'pagination': 'pagination',
        'height': 'height'
    }

    def __init__(self, acknowledgements=None, pagination=None, height=None):  # noqa: E501
        """IbcCoreChannelV1QueryPacketAcknowledgementsResponse - a model defined in Swagger"""  # noqa: E501
        self._acknowledgements = None
        self._pagination = None
        self._height = None
        self.discriminator = None
        if acknowledgements is not None:
            self.acknowledgements = acknowledgements
        if pagination is not None:
            self.pagination = pagination
        if height is not None:
            self.height = height

    @property
    def acknowledgements(self):
        """Gets the acknowledgements of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501


        :return: The acknowledgements of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :rtype: list[IbcCoreChannelV1QueryPacketAcknowledgementsResponseAcknowledgements]
        """
        return self._acknowledgements

    @acknowledgements.setter
    def acknowledgements(self, acknowledgements):
        """Sets the acknowledgements of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.


        :param acknowledgements: The acknowledgements of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :type: list[IbcCoreChannelV1QueryPacketAcknowledgementsResponseAcknowledgements]
        """

        self._acknowledgements = acknowledgements

    @property
    def pagination(self):
        """Gets the pagination of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501


        :return: The pagination of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :rtype: PaginationResponse
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.


        :param pagination: The pagination of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :type: PaginationResponse
        """

        self._pagination = pagination

    @property
    def height(self):
        """Gets the height of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501


        :return: The height of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :rtype: QueryBlockHeight
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.


        :param height: The height of this IbcCoreChannelV1QueryPacketAcknowledgementsResponse.  # noqa: E501
        :type: QueryBlockHeight
        """

        self._height = height

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IbcCoreChannelV1QueryPacketAcknowledgementsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IbcCoreChannelV1QueryPacketAcknowledgementsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
