# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20095(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'denom_traces': 'list[IbcApplicationsTransferV1QueryDenomTracesResponseDenomTraces]',
        'pagination': 'CosmosAuthV1beta1QueryAccountsResponsePagination'
    }

    attribute_map = {
        'denom_traces': 'denom_traces',
        'pagination': 'pagination'
    }

    def __init__(self, denom_traces=None, pagination=None):  # noqa: E501
        """InlineResponse20095 - a model defined in Swagger"""  # noqa: E501
        self._denom_traces = None
        self._pagination = None
        self.discriminator = None
        if denom_traces is not None:
            self.denom_traces = denom_traces
        if pagination is not None:
            self.pagination = pagination

    @property
    def denom_traces(self):
        """Gets the denom_traces of this InlineResponse20095.  # noqa: E501

        denom_traces returns all denominations trace information.  # noqa: E501

        :return: The denom_traces of this InlineResponse20095.  # noqa: E501
        :rtype: list[IbcApplicationsTransferV1QueryDenomTracesResponseDenomTraces]
        """
        return self._denom_traces

    @denom_traces.setter
    def denom_traces(self, denom_traces):
        """Sets the denom_traces of this InlineResponse20095.

        denom_traces returns all denominations trace information.  # noqa: E501

        :param denom_traces: The denom_traces of this InlineResponse20095.  # noqa: E501
        :type: list[IbcApplicationsTransferV1QueryDenomTracesResponseDenomTraces]
        """

        self._denom_traces = denom_traces

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse20095.  # noqa: E501


        :return: The pagination of this InlineResponse20095.  # noqa: E501
        :rtype: CosmosAuthV1beta1QueryAccountsResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse20095.


        :param pagination: The pagination of this InlineResponse20095.  # noqa: E501
        :type: CosmosAuthV1beta1QueryAccountsResponsePagination
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20095, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20095):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
