# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200101(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'client_states': 'list[IbcCoreClientV1QueryClientStatesResponseClientStates]',
        'pagination': 'PaginationResponse'
    }

    attribute_map = {
        'client_states': 'client_states',
        'pagination': 'pagination'
    }

    def __init__(self, client_states=None, pagination=None):  # noqa: E501
        """InlineResponse200101 - a model defined in Swagger"""  # noqa: E501
        self._client_states = None
        self._pagination = None
        self.discriminator = None
        if client_states is not None:
            self.client_states = client_states
        if pagination is not None:
            self.pagination = pagination

    @property
    def client_states(self):
        """Gets the client_states of this InlineResponse200101.  # noqa: E501

        list of stored ClientStates of the chain.  # noqa: E501

        :return: The client_states of this InlineResponse200101.  # noqa: E501
        :rtype: list[IbcCoreClientV1QueryClientStatesResponseClientStates]
        """
        return self._client_states

    @client_states.setter
    def client_states(self, client_states):
        """Sets the client_states of this InlineResponse200101.

        list of stored ClientStates of the chain.  # noqa: E501

        :param client_states: The client_states of this InlineResponse200101.  # noqa: E501
        :type: list[IbcCoreClientV1QueryClientStatesResponseClientStates]
        """

        self._client_states = client_states

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse200101.  # noqa: E501


        :return: The pagination of this InlineResponse200101.  # noqa: E501
        :rtype: PaginationResponse
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse200101.


        :param pagination: The pagination of this InlineResponse200101.  # noqa: E501
        :type: PaginationResponse
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200101, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200101):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
