# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20011(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grants': 'list[GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto]',
        'pagination': 'CosmosAuthzV1beta1QueryGranteeGrantsResponsePagination'
    }

    attribute_map = {
        'grants': 'grants',
        'pagination': 'pagination'
    }

    def __init__(self, grants=None, pagination=None):  # noqa: E501
        """InlineResponse20011 - a model defined in Swagger"""  # noqa: E501
        self._grants = None
        self._pagination = None
        self.discriminator = None
        if grants is not None:
            self.grants = grants
        if pagination is not None:
            self.pagination = pagination

    @property
    def grants(self):
        """Gets the grants of this InlineResponse20011.  # noqa: E501

        grants is a list of grants granted by the granter.  # noqa: E501

        :return: The grants of this InlineResponse20011.  # noqa: E501
        :rtype: list[GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto]
        """
        return self._grants

    @grants.setter
    def grants(self, grants):
        """Sets the grants of this InlineResponse20011.

        grants is a list of grants granted by the granter.  # noqa: E501

        :param grants: The grants of this InlineResponse20011.  # noqa: E501
        :type: list[GrantAuthorizationExtendsAGrantWithBothTheAddressesOfTheGranteeAndGranterItIsUsedInGenesisProtoAndQueryProto]
        """

        self._grants = grants

    @property
    def pagination(self):
        """Gets the pagination of this InlineResponse20011.  # noqa: E501


        :return: The pagination of this InlineResponse20011.  # noqa: E501
        :rtype: CosmosAuthzV1beta1QueryGranteeGrantsResponsePagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this InlineResponse20011.


        :param pagination: The pagination of this InlineResponse20011.  # noqa: E501
        :type: CosmosAuthzV1beta1QueryGranteeGrantsResponsePagination
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20011, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20011):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
