# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'incentivized_packets': 'list[IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId]'
    }

    attribute_map = {
        'incentivized_packets': 'incentivized_packets'
    }

    def __init__(self, incentivized_packets=None):  # noqa: E501
        """QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc - a model defined in Swagger"""  # noqa: E501
        self._incentivized_packets = None
        self.discriminator = None
        if incentivized_packets is not None:
            self.incentivized_packets = incentivized_packets

    @property
    def incentivized_packets(self):
        """Gets the incentivized_packets of this QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc.  # noqa: E501


        :return: The incentivized_packets of this QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc.  # noqa: E501
        :rtype: list[IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId]
        """
        return self._incentivized_packets

    @incentivized_packets.setter
    def incentivized_packets(self, incentivized_packets):
        """Sets the incentivized_packets of this QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc.


        :param incentivized_packets: The incentivized_packets of this QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc.  # noqa: E501
        :type: list[IdentifiedPacketFeesContainsAListOfTypePacketFeeAndAssociatedPacketId]
        """

        self._incentivized_packets = incentivized_packets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QueryIncentivizedPacketsResponseDefinesTheResponseTypeForTheIncentivizedPacketsRpc):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
