# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'val_signing_info': 'ValSigningInfoIsTheSigningInfoOfRequestedValConsAddress'
    }

    attribute_map = {
        'val_signing_info': 'val_signing_info'
    }

    def __init__(self, val_signing_info=None):  # noqa: E501
        """QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod - a model defined in Swagger"""  # noqa: E501
        self._val_signing_info = None
        self.discriminator = None
        if val_signing_info is not None:
            self.val_signing_info = val_signing_info

    @property
    def val_signing_info(self):
        """Gets the val_signing_info of this QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod.  # noqa: E501


        :return: The val_signing_info of this QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod.  # noqa: E501
        :rtype: ValSigningInfoIsTheSigningInfoOfRequestedValConsAddress
        """
        return self._val_signing_info

    @val_signing_info.setter
    def val_signing_info(self, val_signing_info):
        """Sets the val_signing_info of this QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod.


        :param val_signing_info: The val_signing_info of this QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod.  # noqa: E501
        :type: ValSigningInfoIsTheSigningInfoOfRequestedValConsAddress
        """

        self._val_signing_info = val_signing_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuerySigningInfoResponseIsTheResponseTypeForTheQuerySigningInfoRPCmethod):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
