# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TendermintTypesCommit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'str',
        'round': 'int',
        'block_id': 'BlockID',
        'signatures': 'list[CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderCommitSignatures]'
    }

    attribute_map = {
        'height': 'height',
        'round': 'round',
        'block_id': 'block_id',
        'signatures': 'signatures'
    }

    def __init__(self, height=None, round=None, block_id=None, signatures=None):  # noqa: E501
        """TendermintTypesCommit - a model defined in Swagger"""  # noqa: E501
        self._height = None
        self._round = None
        self._block_id = None
        self._signatures = None
        self.discriminator = None
        if height is not None:
            self.height = height
        if round is not None:
            self.round = round
        if block_id is not None:
            self.block_id = block_id
        if signatures is not None:
            self.signatures = signatures

    @property
    def height(self):
        """Gets the height of this TendermintTypesCommit.  # noqa: E501


        :return: The height of this TendermintTypesCommit.  # noqa: E501
        :rtype: str
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this TendermintTypesCommit.


        :param height: The height of this TendermintTypesCommit.  # noqa: E501
        :type: str
        """

        self._height = height

    @property
    def round(self):
        """Gets the round of this TendermintTypesCommit.  # noqa: E501


        :return: The round of this TendermintTypesCommit.  # noqa: E501
        :rtype: int
        """
        return self._round

    @round.setter
    def round(self, round):
        """Sets the round of this TendermintTypesCommit.


        :param round: The round of this TendermintTypesCommit.  # noqa: E501
        :type: int
        """

        self._round = round

    @property
    def block_id(self):
        """Gets the block_id of this TendermintTypesCommit.  # noqa: E501


        :return: The block_id of this TendermintTypesCommit.  # noqa: E501
        :rtype: BlockID
        """
        return self._block_id

    @block_id.setter
    def block_id(self, block_id):
        """Sets the block_id of this TendermintTypesCommit.


        :param block_id: The block_id of this TendermintTypesCommit.  # noqa: E501
        :type: BlockID
        """

        self._block_id = block_id

    @property
    def signatures(self):
        """Gets the signatures of this TendermintTypesCommit.  # noqa: E501


        :return: The signatures of this TendermintTypesCommit.  # noqa: E501
        :rtype: list[CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderCommitSignatures]
        """
        return self._signatures

    @signatures.setter
    def signatures(self, signatures):
        """Sets the signatures of this TendermintTypesCommit.


        :param signatures: The signatures of this TendermintTypesCommit.  # noqa: E501
        :type: list[CosmosBaseTendermintV1beta1BlockEvidenceLightClientAttackEvidenceConflictingBlockSignedHeaderCommitSignatures]
        """

        self._signatures = signatures

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TendermintTypesCommit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TendermintTypesCommit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
