# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TendermintTypesEvidence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duplicate_vote_evidence': 'DeprecatedPleaseUseSdkBlockInsteadEvidenceDuplicateVoteEvidence',
        'light_client_attack_evidence': 'DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidence'
    }

    attribute_map = {
        'duplicate_vote_evidence': 'duplicate_vote_evidence',
        'light_client_attack_evidence': 'light_client_attack_evidence'
    }

    def __init__(self, duplicate_vote_evidence=None, light_client_attack_evidence=None):  # noqa: E501
        """TendermintTypesEvidence - a model defined in Swagger"""  # noqa: E501
        self._duplicate_vote_evidence = None
        self._light_client_attack_evidence = None
        self.discriminator = None
        if duplicate_vote_evidence is not None:
            self.duplicate_vote_evidence = duplicate_vote_evidence
        if light_client_attack_evidence is not None:
            self.light_client_attack_evidence = light_client_attack_evidence

    @property
    def duplicate_vote_evidence(self):
        """Gets the duplicate_vote_evidence of this TendermintTypesEvidence.  # noqa: E501


        :return: The duplicate_vote_evidence of this TendermintTypesEvidence.  # noqa: E501
        :rtype: DeprecatedPleaseUseSdkBlockInsteadEvidenceDuplicateVoteEvidence
        """
        return self._duplicate_vote_evidence

    @duplicate_vote_evidence.setter
    def duplicate_vote_evidence(self, duplicate_vote_evidence):
        """Sets the duplicate_vote_evidence of this TendermintTypesEvidence.


        :param duplicate_vote_evidence: The duplicate_vote_evidence of this TendermintTypesEvidence.  # noqa: E501
        :type: DeprecatedPleaseUseSdkBlockInsteadEvidenceDuplicateVoteEvidence
        """

        self._duplicate_vote_evidence = duplicate_vote_evidence

    @property
    def light_client_attack_evidence(self):
        """Gets the light_client_attack_evidence of this TendermintTypesEvidence.  # noqa: E501


        :return: The light_client_attack_evidence of this TendermintTypesEvidence.  # noqa: E501
        :rtype: DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidence
        """
        return self._light_client_attack_evidence

    @light_client_attack_evidence.setter
    def light_client_attack_evidence(self, light_client_attack_evidence):
        """Sets the light_client_attack_evidence of this TendermintTypesEvidence.


        :param light_client_attack_evidence: The light_client_attack_evidence of this TendermintTypesEvidence.  # noqa: E501
        :type: DeprecatedPleaseUseSdkBlockInsteadEvidenceLightClientAttackEvidence
        """

        self._light_client_attack_evidence = light_client_attack_evidence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TendermintTypesEvidence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TendermintTypesEvidence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
