# coding: utf-8

"""
    HTTP API Console

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TheIdentifiedFeesForTheIncentivizedPacket(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'packet_id': 'UniquePacketIdentifierComprisedOfTheChannelIDPortIDAndSequence',
        'packet_fees': 'list[PacketFeeContainsICS29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers]'
    }

    attribute_map = {
        'packet_id': 'packet_id',
        'packet_fees': 'packet_fees'
    }

    def __init__(self, packet_id=None, packet_fees=None):  # noqa: E501
        """TheIdentifiedFeesForTheIncentivizedPacket - a model defined in Swagger"""  # noqa: E501
        self._packet_id = None
        self._packet_fees = None
        self.discriminator = None
        if packet_id is not None:
            self.packet_id = packet_id
        if packet_fees is not None:
            self.packet_fees = packet_fees

    @property
    def packet_id(self):
        """Gets the packet_id of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501


        :return: The packet_id of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501
        :rtype: UniquePacketIdentifierComprisedOfTheChannelIDPortIDAndSequence
        """
        return self._packet_id

    @packet_id.setter
    def packet_id(self, packet_id):
        """Sets the packet_id of this TheIdentifiedFeesForTheIncentivizedPacket.


        :param packet_id: The packet_id of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501
        :type: UniquePacketIdentifierComprisedOfTheChannelIDPortIDAndSequence
        """

        self._packet_id = packet_id

    @property
    def packet_fees(self):
        """Gets the packet_fees of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501


        :return: The packet_fees of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501
        :rtype: list[PacketFeeContainsICS29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers]
        """
        return self._packet_fees

    @packet_fees.setter
    def packet_fees(self, packet_fees):
        """Sets the packet_fees of this TheIdentifiedFeesForTheIncentivizedPacket.


        :param packet_fees: The packet_fees of this TheIdentifiedFeesForTheIncentivizedPacket.  # noqa: E501
        :type: list[PacketFeeContainsICS29RelayerFeesRefundAddressAndOptionalListOfPermittedRelayers]
        """

        self._packet_fees = packet_fees

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TheIdentifiedFeesForTheIncentivizedPacket, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TheIdentifiedFeesForTheIncentivizedPacket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
