name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Get Tag Version
      id: get_tag_version
      run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"

    - name: Get Tag Description
      id: get_tag_description
      run: |
        TAG_NAME=${{ steps.get_tag_version.outputs.version }}
        DESCRIPTION=$(git log --format=%s -1 "$TAG_NAME")  
        echo "::set-output name=description::$DESCRIPTION"

    - name: Print Tag Information
      run: |
        echo "Tag Version:  ${{ steps.get_tag_version.outputs.version }}"
        echo "Tag Description: ${{ steps.get_tag_description.outputs.description }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
       tag_name: ${{ steps.get_tag_version.outputs.version }}
       release_name: Release ${{ steps.get_tag_version.outputs.version }}
       body: ${{ steps.get_tag_description.outputs.description }}
       draft: false
       prerelease: false